// <auto-generated />
namespace IT_Proekt_2020.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class klient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(klient));
        
        string IMigrationMetadata.Id
        {
            get { return "202012131112104_klient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
