// <auto-generated />
namespace IT_Proekt_2020.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class poeni : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poeni));
        
        string IMigrationMetadata.Id
        {
            get { return "202012132344033_poeni"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
